### ISSUE TITLE
Is there any chance to support Inoreader?

### ISSUE THREAD

**Issue by horacioj** [noinnion/greader#108]
Hi,
Given that you currently support Feedly and The Old Reader.
Is there any chance you could also support http://www.inoreader.com/ ? I find your Android app better than theirs.. 
Thanks

**Comment by joshg253** [comment]
You can try their (also apparently abandoned) News+ app: https://github.com/noinnion/newsplus

I use it daily for Inoreader and it has plugins for others as well.

**Comment by horacioj** [comment]
Thank you. Unfortunately, it requires login with user & pass, but I'm signing in with a google account.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
