### ISSUE TITLE
Mark read when scrolling 

### ISSUE THREAD

**Issue by s0m3guy** [noinnion/greader#116]
Recently flashed a new custom ROM version and downloaded gReader freshly again. Now after I activated this option it does not seem to work. Checked it but scrolling does nothing, articles stay unread. Tried restarting the app, nothing.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by s0m3guy** [comment]
Yea I recently switched to Palabre, great app!

Mit freundlichen Grüßen
Ilja Golland

2016-03-19 10:46 GMT+01:00 ajoe <notifications@github.com>:

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
