### ISSUE TITLE
Switching article view mode has no affect 

### ISSUE THREAD

**Issue by DeeHants** [noinnion/greader#121]
When looking at articles, I sometimes need to switch between feed and web view.
This no longer works on Android 5.1.1. The progress bar appears, progresses, then disappears with no change to the view.
The default view setting works as expected. 
This is using gReader 4.2.0, and that same  version works fine on Android 4.4.

**Comment by Stift** [comment]
Duplicate to #114 and #115

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
