### ISSUE TITLE
Google Mobilizer 

### ISSUE THREAD

**Issue by apatternjugglers** [noinnion/greader#125]
Hi , I suspect it's likely to be at Google's end and beyond your control, but as of about an hour ago, attempts by GReader Pro to use the Google Mobilizer are being served by googleweblight instead. 
This appears to be a vastly inferior mobilizer:is there any prospect of updating the available mobilizers?

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
