### ISSUE TITLE
Enhancements for full article viewing

### ISSUE THREAD

**Issue by shikhanshu** [noinnion/greader#127]
Scenario:

1. I click on an article in the article list to view it
2. I double-click inside the article to load the full article - **ISSUE: The preview text that showed in the condensed article view does not show in this full article view, it shows the text AFTER the preview text**
3. I click on a hyperlink in the full article view to open it in the internal browser (not external)
4. I am done viewing the link, I hit the back button - **ISSUE: It goes back straight to the article list. It should go back to the full article view.**

It will be a great enhancement to reading experience if the above two issues can be fixed.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by shikhanshu** [comment]
Thanks. How do i male YouTube links open with YouTube instead of in-app? I
don't see the option to toggle that anymore

**Comment by noinnion** [comment]
Settings->Reading Preferences->Article Controls
