### ISSUE TITLE
Bellows/ behavior

### ISSUE THREAD

**Issue by figueroajesus** [noinnion/greader#131]
gReader occasionally has a weird "bellows" kind of behaviour reading articles that are stored in offline cache. The issue can usually be resolved by backing out of an article and re-opening it. Here's a link how the bellows behavior looks:

**Comment by figueroajesus** [comment]
Forgot the link: http://imgur.com/3BIEXks

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by figueroajesus** [comment]
Thanks for the update. I'll test this on my phone for a few days and close this if the issue is resolved.

**Comment by figueroajesus** [comment]
The beta is working great and this issue seems to be fixed.
