### ISSUE TITLE
Request Custom CSS

### ISSUE THREAD

**Issue by ghost** [noinnion/greader#134]
Can you please add CSS settings for read mode? The text is too small for me, spacing and margin too. I know there floating button that can make text bigger, but it's too big.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
could you send me a screenshot?
