### ISSUE TITLE
Feeds updating too slow 

### ISSUE THREAD

**Issue by naore** [noinnion/greader#136]
The feeds' updating is always too slow in my phone. I am in China now and use two VPN lines in Hong Kong and Montreal(Canada) to update feeds, but it's still very slow. I am sure my VPN is fast. Is there any way can accelate the updating? Best wishes.

**Comment by ajoe** [comment]
GReader is DEAD!

Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available.
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
