### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by meridius** [noinnion/greader#137]
Sometimes I have an issue with text of the page not being fully rendered and when I scroll the bottom there is a big gray gap and when I scroll further the text starts to shrink. 
You can see that best at following screencasts https://youtu.be/siu_vXN0xEc

**Comment by ajoe** [comment]
GReader is DEAD!

Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available.
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by meridius** [comment]
Ok, thanks for the tips. Palabre seems fine

**Comment by noinnion** [comment]
here is the latest beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by nweinberg** [comment]
Has anyone installed the new beta? Does it work at all?

**Comment by figueroajesus** [comment]
I have the beta installed on my LG G4. No problems so far.

**Comment by nweinberg** [comment]
Installed the beta on my nexus 6p. Works much better than 4.2, a lot of the rendering bugs went away. I'm going to pay for Pro to encourage the dev to keep at it. This app is too important to let die, and there are no decent alternatives I can find.
