### ISSUE TITLE
Mark read when scrolling missing

### ISSUE THREAD

**Issue by gimley** [noinnion/greader#144]
I am using Nexus 5x and do not see an option to enable it.
I even tried on pro version.

**Comment by noinnion** [comment]
click on title in actionbar

**Comment by Matth7878** [comment]
Before updating beta mark read on scroll was marking articles as read if there was only one screen of articles and scrolling was not possible. With latest beta when you see end of articles list without scrolling (list shorter than your screen) greader do not mark articles as read and you have to mark them manually.

For me having to mark articles manually is the correct way of handling it since you can't scroll. So if you open articles list by error you don't end with articles marked as read by error. Please do not change it as @gimley is requesting or let user set a behavior for this case.
Marking read articles when you didn't scroll make the feature useless and that's why I didn't use it before. Having to mark read for short list is easy and quick, unmarking articles is not!

**Comment by gimley** [comment]
Ah, thanks found it.
