### ISSUE TITLE
When open article in cashed view just a random paragraph appears.

### ISSUE THREAD

**Issue by sysadm01** [noinnion/greader#230]
When open article in cashed view just a random paragraph appears. If I switch to Feed view, then I can see whole article.

**Comment by aisbergde** [comment]
Yes, this is a big issue. It prevents from using the offline functionality. First I need to select the Feed view to get a description, because the description is not part of the cash. Then I switch to cache to get the content and it would be better to also se the description there (other readers are able to do) . On some feed source the cache contains the whole article, but on other feeds only one randomly paragraph. Hard to use, especially when mixing articles from different feeds while reading.

**Comment by aisbergde** [comment]
It looks like loading the normal view but not the simple view can solve the problem for me
