### ISSUE TITLE
Feedly Google login is broken

### ISSUE THREAD

**Issue by gsanchezu** [noinnion/greader#312]
Evento trying yo login with Google inti Feedly the following error id thrown:
403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

Learn more

**Comment by sgamon** [comment]
Same for me.

**Comment by Dreadaxe** [comment]
Same

**Comment by imiara** [comment]
Same for me.

**Comment by aarongustafson** [comment]
Yep.

**Comment by aarongustafson** [comment]
Any updates on this? I just did the paid upgrade and I can't use it.

**Comment by imiara** [comment]
Only a workaround :
Login to feedly.com with a browser and add a feedly login. Then use the
feedly login instead of google.

On Sep 13, 2017 5:37 PM, "Aaron Gustafson" <notifications@github.com> wrote:

Any updates on this? I just did the paid upgrade and I can't use it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/noinnion/greader/issues/312#issuecomment-329188389>,
or mute
the thread

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
