### ISSUE TITLE
Podcast cannot be downloaded

### ISSUE THREAD

**Issue by zavjah** [noinnion/greader#357]
Hi,

Since few weeks when I try to download a podcast from www.treffpunkt-leben.org I get an error, that the file is not existing (see attached log) although it is. When I paste the url from the log file directly into chrome the podcast is started and can be downloaded.

Could you please look into this? It is not with other podcast but will the all from their site. Untill few weeks ago download was possible even here.

Thx,
Zavjah
[log_1521892466479.txt](https://github.com/noinnion/greader/files/1844340/log_1521892466479.txt)

**Comment by Locash** [comment]
I looked into this issue a little more and noticed the the feed address that those podcast come from does not Validate! A rss/atom feed needs to validate and NOT have syntax errors, otherwise rss readers will have issues. This happens ALOT. Here is the validation address by w3c ( they set the standards for rss/atom feeds....so they know if there is a issue.) You will want the sites webmaster at www.treffpunkt-leben.org to know about this issue. Anytime you have a feed issue check if the feed validates, if not that's likely the issue causing problems. 
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.treffpunkt-leben.org%2Fpredigten%2Fpodcast_all.xml

**Comment by zavjah** [comment]
Hi,

I had contact with the programers and they fixed the feed. Please check this link here: https://www.treffpunkt-leben.org/predigten/podcast.xml

When I add this new feed into greader I can stream the feed but the download still fails. Cod you please check it again?

Cheers,
Timeneznas

**Comment by Locash** [comment]
I checked and I was able to download a cast. It seems to be a issue on your end. I  would say it is likely a folder issue. Try this if you have a external SD card.
........ Go to settings >Cache>Offline Content Storage /Select manual...then in the drop down menu select the longer directory.
If not you will need to do a clean install off the app and before you reinstall it. Do a folder search for anything Greader and delete it manually including .files that are hidden. 
![quickmemo _2018-06-16-10-34-19](https://user-images.githubusercontent.com/30946440/41500089-5e58c8d8-7151-11e8-9000-83466b86576d.png)

**Comment by zavjah** [comment]
I have tried both options. I'd didn't work even after a clean install. 
![screenshot_greader_pro_20180616-200925](https://user-images.githubusercontent.com/37732361/41501282-e102a9b6-71a1-11e8-8f30-a6791481fd27.png)

This happens only with this feed though. I can download other feed like a charm.

**Comment by Locash** [comment]
What app version are you using?

**Comment by zavjah** [comment]
Hi,

I am using Ng 4.3.1 pro and Feedly. I logged out and logged in again without https. Then I removed the podcast and add it again and tried the download again. No change. I can download any podcast from here though: www.tagesschsu.de/export/podcast/tagesschau. Only this one stopped working few weeks ago without any reason known to me.

Thx
