### ISSUE TITLE
Cannot authenticate with Google for Feedly sync

### ISSUE THREAD

**Issue by smimon** [noinnion/greader#365]
I am receiving a 403 error, disallowed_useragent, when trying to sync with Feedly using Google authentication.

Full error message: https://prntscr.com/jk099l

I'm running Android 8.0.0 on a Huawei Mate 9 Pro, 1st April 2018 security patch.

**Comment by alexander-milovidov** [comment]
I have the same issue on ASUS Zenfone ZE554KL (Android 8).

**Comment by Locash** [comment]
The only way currently fix this issue is to pull your Opml of feeds and open a NEW Feedly account via a regular email address way. Logging into Feedly that way still works as with doing it that way with The old reader.
The app appears to be abandoned as of current so a update to fix the google oauth issue will not be coming any time soon!

**Comment by smimon** [comment]
Thanks. That's what I ended up doing in the end.

**Comment by thoraxe** [comment]
Wow that's... garbage-y.

Is there another offline reader app?

**Comment by Locash** [comment]
@thoraxe. I used a reader called "Feed Me" for awhile it did the job but not like Greader. So I came back to Greader because it allows direct access to the article by in app webview and offline by downloading a simplified or normal page versions of the the complete article. Most rss readers just grab whats available in the rss feed, a short description. If you want to read the full article its off to the browser out of app.

https://play.google.com/store/apps/details?id=com.seazon.feedme

**Comment by KUTlime** [comment]
Solution for 403: https://github.com/noinnion/greader/issues/373#issuecomment-427557271

**Comment by KUTlime** [comment]
Would be somebody interested to develop an Open-Source alternative to gReader based on Xamarin.Forms? We know how it should look like, we know what the feature should be like, so we just need to code it.

**Comment by Mahaldo** [comment]
This is already fixed in January 2021.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
