### ISSUE TITLE
Premium Licence not recognised when using LineageOS + gmicro + Yalp store

### ISSUE THREAD

**Issue by x7i7l** [noinnion/greader#366]
I'm not sure if you intend to support gmicro users but the premium licence is not recognised. It says "Licence checking not passed" even though I purchased pro a while back. On this device I use Lineage OS + Gmicro and downloaded greaser through the yalp store.

Device: Samsung Galaxy Tab 2
OS: Lineage OS 13 + gmicro

**Comment by Locash** [comment]
It is a "You Not Knowing How things Work Issue"( no offense). I had this same issue with a app not being recognized with substratum addons. If the apk was obtained from Yalp store it wouldn't pass....if I got it from the Google play store it did. So I got on MicroG GitHub and asked  and tinkered ALOT! 
By the way if you do not have Google play store... a licence check can not be done. Yalp does not do that, Yalp is intended to be a  way to download apks from the play store without Google services operating on the device, So Google services AND the play store is needed for a licence check. The apps licence needs to correspond to the account that downloaded it, since most who use Yalp use the default account to attain the apk it will not pass the licence check even if it is an Free app and it asks Google play store to do so.
Developers still may want a licence check so the app cannot be manipulated and the ad revenue goes to someone else, as long as the app has to be verified and pass a licence check via Google services there will Likley be NO pirated Or altered versions of their app floating around and being downloaded , installed and ran\played. 

Anyways MicroG was not designed to work with Google play store all though it can with certain versions and set up. Good thing someone did make some changes so one could use Google play store with MicroG more easily and @ale5000 is his name he created a flashable MicroG installer that has Google play integrated check it out.
https://forum.xda-developers.com/android/development/microg-unofficial-installer-t3432360

Here is a apk version of Greader pro beta that needs no license check( it is the last beta version to come out) It is the version I use and it works great. The site actually downloads the apk to you, without a bunch of crap and ads. When you click (download) it actually starts. This will solve your problem without having to change anything other then uninstalling the old version and installing this version.
http://m.apkhere.com/app/com.noinnion.android.greader.readerpro

By the way MicroG was developed so a person could have privacy and use Non Google apps that required play services libraries to run. Once you start using Google apps with MicroG, it is defeating the purpose of what MicroG was for. A person mine as well use regular Google play services and neuter it as much as they can and practice safe device habits like always use VPN and not use cellular services on device period your privacy is gone once you do that and all other measures are made useless. Many commit privacy and security No-no's like using identifiable factors online, logging on in a way so their IP address is easily identifiable or using the GPS on a device, a bunch of apps and Google grabs your location info right away. Once a that's out there...what's the point of the rest of the stuff on does in the name of privacy?
Most use MicroG to tinker and that's it... whether they admit it or not because most people do things that circumvent privacy and security measures they think they are doing in good faith but is actually pointless!

If I stated anything wrong anyone, please let me know! That's how people learn and I welcome it!

**Comment by x7i7l** [comment]
Hi Locash

thanks for the info. I was posting the issue because I would like 
developers to support alternative avenues than google play for the 
distribution of apps, perhaps devs are unaware.

With regards to MicroG I see the project as an attempt to chip away at 
google's dominance of the android platform. If I wanted to completely 
avoid google I would just use LineageOS without MicroG or Gapps. In this 
case I am limited to f-droid but for my work there are certain 
closed-source apps which I need to run - MicroG provides a good compromise.

**Comment by Locash** [comment]
@x7i7l  
       I wish the developer would dig into some of the issues also.......but it does not seem that will be happening since the last app updates were in 2016 for Greader and 2015 for News+. 
Last time @noinnion contributed to anything on GitHub was April 26, 2016.
It seems that development for Greader or News+ has been abandoned......a Houdini project!
Makes my 💓 break for Greader to be collecting dust and being left unattended. It is a great reader with permanent hiccups now!

**Comment by Friedi** [comment]
Sometimes people/developer find new sense in other aspects of life. Sometimes unexpected things happen. May he be healthy and happy wherever he is.

**Comment by x7i7l** [comment]
I wish the developer would make the code open source so a community could revive their excellent work.

Best regards,

Adrienne

Sent from my phone

31 Jul 2020 15:41:40 Friedi <notifications@github.com>:

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
