### ISSUE TITLE
Podcast scheduling

### ISSUE THREAD

**Issue by inferno493** [noinnion/greader#369]
Is there a way to schedule podcast downloads?

**Comment by Locash** [comment]
You can have all downloaded when it comes available. With pro version.
Settings>offline reading>load audio
Pro version beta for free. http://m.apkhere.com/app/com.noinnion.android.greader.readerpro

**Comment by Locash** [comment]
Yes on pro version. Settings>offline reading>load audio
You can also download all the feeds ,images for viewing offline.
Pro version
http://forum.teamdroidcommunity.com/viewtopic.php?t=34
Direct download
http://forum.teamdroidcommunity.com/download/file.php?id=6&sid=fc37646d8e4ec09e893772f801437054

**Comment by inferno493** [comment]
Thanks for the reply. I have pro version and found the podcast controls after looking in the settings as you outlined. Is there a way to control the number of podcasts that are downloaded at a time? I have limited storage space and would like to keep only the three most current stored locally.

**Comment by Locash** [comment]
Sadly no. You can have those podcast downloaded to your external SD card though if that helps.
I use podcast addict which is great for the podcasts. I wish I could combine both because PA does not have the setup like Greader  for RSS feed reading. It Only has direct RSS feed  downloading not a cloud option like through feedly or old reader which causes many feed issues because most feeds are poorly written with many errors causing an app problems.

**Comment by inferno493** [comment]
I am currently using Doggcatcher for podcasts but gReader is my most heavily used app. I thought it would be great to have a full-featured podcast client baked in. You have done a fantastic job with creating an incredible RSS reader. Perhaps you should consider making a second app that could be integrated with gReader.

**Comment by Locash** [comment]
I did not create Greader or have anything to do with noinnion. I just try to help those with issues with the app since the App has been Abandoned since 2016. It is true the Greader is the best reader by far. With social media having algorithms that feed you a steam of paid for bubble news. The only way to go is RSS feeds and casts so one may control the news they receive.

**Comment by inferno493** [comment]
My mistake, thanks for your assistance!

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

Please create a feature request issue, if you want any new features.
