### ISSUE TITLE
Can't buy pro version

### ISSUE THREAD

**Issue by GGboomers** [noinnion/greader#390]
Click on Premium to display a page (as shown in the picture), but it cannot be redirected to the Google Store and cannot be purchased.

![S10210-13532463](https://user-images.githubusercontent.com/77922714/107471997-1ae82a80-6ba9-11eb-872a-850401fcc1ba.jpg)

**Comment by noinnion** [comment]
Where are you located?

**Comment by k3iran** [comment]
I see an option for greader premium. But where is my Greader Pro app? I bought it years ago and used it for a time until it was abandoned.

**Comment by noinnion** [comment]
Unfortunately the Pro version was removed by Google from Play Store because of old implementation. You can still find the the latest Pro version here https://github.com/noinnion/greader/tree/master/apk

We decided to maintain only free version with Premium to finance the development of the app. For reparation we offer you 1 year free trial for the annual subscription. Please send a message to noinnion@gmail.com. I appologize for the inconvenience.
