### ISSUE TITLE
About Premium

### ISSUE THREAD

**Issue by StrollStars** [noinnion/greader#397]
I have buy and use a earlier Pro version, can I migrate to the premier now?

**Comment by folkenne** [comment]
Good question, since we can not get our premium application back

**Comment by aslafy-z** [comment]
Same here. would love to get back the Pro version.

**Comment by noinnion** [comment]
Unfortunately the removal was done by Google because of old implementation and missing legal stuffs. You could still sideload the latest pro version here https://github.com/noinnion/greader/tree/master/apk

We can offer you 1 year free subscription with a promo code. Please write to noinnion@gmail.com
