### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by alxchk** [noinnion/greader#59]
I'm using a lot of sources. On desktop I use filters  and more then 90% goes to /dev/null. Is there anyway to do so with greater? Maybe in pro?

**Comment by noinnion** [comment]
I' m not sure what your problem is. What do you want to filter?

**Comment by alxchk** [comment]
For example, for all my feeds I want to filter articles which contains word CVE in subject (with tag CVE), with words IDA Pro in body (with tag IDA) and so on

**Comment by noinnion** [comment]
In gReader pro you can only add tags to articles manuelly. Unfortunately
there is no automatic tag feature.

On Mon, Aug 17, 2015 at 10:19 PM, Oleksii Shevchuk <notifications@github.com

**Comment by luisfl** [comment]
I don't like the Pope. 
I don't care about the Pope.
I am not interesting in anything the Pope has to say.
I don't want to know where the Pope went.

So, I want greader to hide/remove/forget any article that has "Pope" in the title. Easy.

I am actually surprised this is not a basic feature of any RSS reader, much less a mature one like greader.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
THere is a search filter in gReader, please try v5.1.4
When you search for something, press the + button save the search
