### ISSUE TITLE
Repeat

### ISSUE THREAD

**Issue by medico89** [noinnion/greader#74]
Articles repeat of 5to 8 Times

**Comment by noinnion** [comment]
could you tell me the feeds?

**Comment by dstahlke** [comment]
I see this too, on the Hackaday feed.  Articles show up one day, then repeat the next day (or two days?), and sometimes show up again a third time.

**Comment by noinnion** [comment]
what service do you use? feedly? the old reader? , local?
On Apr 15, 2016 7:29 PM, "Dan Stahlke" <notifications@github.com> wrote:

I see this too, on the Hackaday feed. Articles show up one day, then repeat
the next day (or two days?), and sometimes show up again a third time.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/noinnion/greader/issues/74#issuecomment-210556000>

**Comment by dstahlke** [comment]
local.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
